language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
addons:
  postgresql: "9.3"
before_script:
  - cp travis-connect-info.json connect-info.json
  - psql -c 'create database test_db;' -U postgres  